// 리셋 후 테스트를 반복할 때 항상 같은 구성으로 채워 넣기 위한 고정 더미데이터입니다.
// 실제 명단 이름을 사용하되, 실제 행사 데이터가 아니라 테스트 전용입니다.
export type DummyEntry = {
  department: string;
  name: string;
  content: string;
  group_type: "draw" | "no_draw";
};

export const DUMMY_ENTRIES: DummyEntry[] = [
  { department: "여의도지역단", name: "박성주", content: "디지털 전환에 발맞춰, 대면 영업 중심에서 온오프라인 병행 영업으로 자연스럽게 축이 옮겨가야 한다고 생각합니다.", group_type: "draw" },
  { department: "경기지역단", name: "박양수", content: "네넵", group_type: "draw" },
  { department: "동탄오산지역단", name: "김장우", content: "ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ", group_type: "draw" },
  { department: "평택지역단", name: "유영민", content: "배고파요", group_type: "draw" },
  { department: "방배지역단", name: "하경란", content: "개인의 성과보다 팀 전체의 시너지를 우선하는 문화로 전환되었으면 합니다. 서로 돕는 조직이 되길 기대합니다.", group_type: "draw" },
  { department: "안양평촌지역단", name: "최재호", content: "지역단 간 경쟁보다 우수 사례를 함께 공유하는 협력 문화로 전환되면 전체 조직의 성장 속도가 빨라질 것 같습니다.", group_type: "draw" },
  { department: "경원FP센터", name: "이승민", content: "성과 보고 방식이 숫자 나열이 아니라 실제 변화 사례 중심으로 바뀌었으면 합니다.", group_type: "no_draw" },
  { department: "강남FP센터", name: "홍동우", content: "센터 운영이 관리 중심에서 현장 서포트 중심으로 축이 옮겨가면 좋겠습니다.", group_type: "no_draw" },
  { department: "컨설팅P", name: "조가현", content: "본사 주도 방식에서 현장의 자율성을 존중하는 컨설팅 방식으로 전환되었으면 합니다.", group_type: "no_draw" },
  { department: "강동지역단", name: "김용철", content: "변화에 대한 두려움보다 변화가 주는 기회에 집중하는 조직이 되었으면 좋겠습니다.", group_type: "draw" },
  { department: "서초지역단", name: "황경석", content: "수직적인 보고 체계보다 수평적인 협업 구조로 축이 옮겨가면, 현장의 목소리가 더 빠르게 전달될 것 같습니다.", group_type: "draw" },
  { department: "교육지원P", name: "김미정", content: "오프라인 집합 교육 위주에서 필요할 때 바로 들을 수 있는 온디맨드 학습으로 바뀌면 좋겠습니다.", group_type: "no_draw" },
  { department: "조직육성P", name: "채호성", content: "일방적인 교육 커리큘럼보다 지역단 맞춤형 육성 프로그램으로 전환되길 바랍니다.", group_type: "no_draw" },
  { department: "목동지역단", name: "최문규", content: "신입 설계사 육성 방식이 주입식 교육에서 현장 동행 중심으로 바뀌면 정착률이 훨씬 높아질 것 같습니다.", group_type: "draw" },
  { department: "리크루팅추진P", name: "문용섭", content: "채용 기준이 스펙 중심에서 현장 적합성 중심으로 바뀌었으면 합니다.", group_type: "no_draw" },
  { department: "영업추진P", name: "이문섭", content: "정량 지표 중심 관리에서 정성적 피드백을 함께 반영하는 방식으로 전환되면 좋겠습니다.", group_type: "no_draw" },
  { department: "영업지원P", name: "이기웅", content: "본사 지원 부서도 현장 방문을 정례화해서 실제 어려움을 더 가까이서 체감했으면 합니다.", group_type: "no_draw" },
  { department: "송파지역단", name: "이승열", content: "고객 응대 매뉴얼 중심에서 고객 공감 중심으로 전환되면 좋겠습니다. 형식보다 진심이 통하는 영업 문화를 만들고 싶습니다.", group_type: "draw" },
  { department: "금천광명지역단", name: "이창신", content: "본사와 현장 사이의 소통 방식이 공지 위주에서 쌍방향 피드백 구조로 바뀌었으면 좋겠습니다.", group_type: "draw" },
  { department: "분당지역단", name: "이태형", content: "단기 실적 중심 문화에서 고객 평생가치를 중시하는 문화로 전환되길 바랍니다.", group_type: "draw" },
  { department: "수원지역단", name: "유창효", content: "회의를 위한 회의가 줄고, 실행 중심의 짧고 잦은 소통으로 바뀌었으면 합니다.", group_type: "draw" },
  { department: "강남지역단", name: "신종훈", content: "성과 중심 평가에서 성장 중심 피드백 문화로 전환되면 좋겠습니다. 실패를 두려워하지 않고 도전할 수 있는 분위기가 만들어지길 바랍니다.", group_type: "draw" },
  { department: "없음", name: "박가짜", content: "가짜 사번으로 접수했을 때 처리가 잘 되는지 확인하기 위한 테스트입니다.", group_type: "draw" },
  { department: "테스트지역단", name: "김테스트", content: "명단에 없는 이름으로 접수했을 때 의심 표시가 잘 뜨는지 확인하기 위한 테스트 데이터입니다.", group_type: "draw" },
  { department: "강서지역단", name: "이범식", content: "실적 압박보다 장기적인 고객 관계를 우선하는 평가 기준으로 전환되었으면 합니다.", group_type: "draw" },
  { department: "구리지역단", name: "최준호", content: "문제가 생겼을 때 책임 소재를 따지기보다 함께 해결하는 문화로 전환되길 바랍니다.", group_type: "draw" },
  { department: "대전지역단", name: "박화주", content: "변화 자체를 관리 대상으로만 보지 말고, 구성원이 주도하는 변화로 전환되었으면 합니다.", group_type: "draw" },
  { department: "청주지역단", name: "신미진", content: "asdf", group_type: "draw" },
  { department: "순천지역단", name: "송상형", content: "ㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎ", group_type: "draw" },
  { department: "제주지역단", name: "김도영", content: "퇴근하고싶다", group_type: "draw" },
  { department: "조직순증P", name: "오종철", content: "본사 조직도 성과 지표를 매출 숫자 외에 현장 만족도까지 함께 반영했으면 합니다.", group_type: "no_draw" },
  { department: "휴먼센터지원P", name: "문준영", content: "지원 업무가 요청 처리 중심에서 선제적 문제 발굴 중심으로 바뀌면 좋겠습니다.", group_type: "no_draw" },
  { department: "효율추진P", name: "차원철", content: "효율화가 인력 감축이 아니라 업무 방식 개선으로 이어지는 방향이었으면 합니다.", group_type: "no_draw" },
  { department: "고객활동P", name: "유인선", content: "단발성 이벤트보다 꾸준한 고객 관계 관리 활동으로 축이 옮겨가면 좋겠습니다.", group_type: "no_draw" },
  { department: "수도권1영업추진P", name: "유훈", content: "영업 지원이 본사 주도가 아니라 현장 요청 기반으로 움직였으면 합니다.", group_type: "no_draw" },
  { department: "동부CSM지원P", name: "박수용", content: "CSM 업무가 사후 응대 중심에서 사전 케어 중심으로 전환되었으면 좋겠습니다.", group_type: "no_draw" },
  { department: "서부영업추진P", name: "김덕윤", content: "지역 간 자원 배분이 더 투명하게 공유되는 구조로 바뀌면 좋겠습니다.", group_type: "no_draw" },
  { department: "충청권지원P", name: "최용훈", content: "본사와 현장의 온도차를 줄이기 위해 정기적인 현장 파견 근무를 도입하면 좋겠습니다.", group_type: "no_draw" },
  { department: "미확인지역단", name: "이허구", content: "가짜 이름으로 접수했을 때 의심 표시가 잘 뜨는지 확인하는 테스트 데이터입니다.", group_type: "draw" },
  { department: "없음", name: "최없음", content: "사번 조회에 실패하는 케이스를 확인하기 위한 두 번째 테스트 데이터입니다.", group_type: "draw" },
  { department: "안산지역단", name: "이현진", content: "위기 대응이 사후 처리 중심에서 사전 예방 중심으로 전환되었으면 합니다.", group_type: "draw" },
  { department: "판교성남지역단", name: "허원영", content: "본사 정책이 일괄적으로 내려오기보다, 지역 특성을 반영해 유연하게 적용되는 구조로 바뀌었으면 합니다.", group_type: "draw" },
  { department: "춘천원주지역단", name: "박성우", content: "경력 설계사 중심에서 신입도 함께 성장할 수 있는 멘토링 문화로 축이 옮겨가면 좋겠습니다.", group_type: "draw" },
  { department: "해운대지역단", name: "배철용", content: "실적표 중심 회의에서 사례 중심 학습 회의로 바뀌면 훨씬 도움이 될 것 같습니다.", group_type: "draw" },
  { department: "일산지역단", name: "황진택", content: "연공서열 중심 승진 구조에서 역량과 성과 중심으로 바뀌었으면 좋겠습니다.", group_type: "draw" },
  { department: "서울지역단", name: "강종우", content: "보여주기식 실적 발표보다 실제 고객 만족도를 중심에 두는 문화가 자리잡길 바랍니다.", group_type: "draw" },
  { department: "은평지역단", name: "조영덕", content: "개인 플레이보다 팀 단위로 협업하는 영업 방식으로 전환되면 시너지가 커질 것 같습니다.", group_type: "draw" },
  { department: "노원지역단", name: "최정화", content: "고객 데이터 활용이 소극적인데, 이를 적극 활용한 맞춤형 컨설팅 영업으로 축이 옮겨가면 좋겠습니다.", group_type: "draw" },
  { department: "부평지역단", name: "김수종", content: "지역단 간 정보 공유가 폐쇄적인데, 우수 노하우를 서로 공유하는 개방적 문화가 필요합니다.", group_type: "draw" },
  { department: "WM지역단", name: "김필수", content: "단기 목표 달성보다 고객과의 신뢰를 쌓는 과정 자체를 평가하는 문화로 전환되면 좋겠습니다.", group_type: "draw" },
  { department: "서부CSM지원P", name: "김현석", content: "민원 처리 프로세스가 단순화되면 현장과 고객 모두에게 도움이 될 것 같습니다.", group_type: "no_draw" },
  { department: "가짜지역단", name: "정허위", content: "세 번째 테스트 배치의 두 번째 가짜 이름 접수 데이터입니다.", group_type: "draw" },
  { department: "수도권1CSM지원P", name: "주양식", content: "CSM 지원 인력 배치가 지역별 편차 없이 고르게 이뤄졌으면 좋겠습니다.", group_type: "no_draw" },
  { department: "해운대연수소지원P", name: "김형준", content: "연수소 운영이 본사 일정 위주가 아니라 지역 수요 기반으로 유연해졌으면 합니다.", group_type: "no_draw" },
  { department: "울산지역단", name: "윤호성", content: "고객 상담이 상품 설명 중심에서 생애 설계 중심으로 전환되면 좋겠습니다.", group_type: "draw" },
  { department: "신촌지역단", name: "조희승", content: "경쟁 중심 조직문화에서 협업과 상생을 중시하는 문화로 축이 옮겨가길 바랍니다.", group_type: "draw" },
  { department: "인천지역단", name: "권희열", content: "현장의 작은 성공 사례도 전사적으로 공유되는 문화가 되었으면 합니다.", group_type: "draw" },
  { department: "남동지역단", name: "이장열", content: "세대 간 소통 방식 차이를 좁힐 수 있는 자리가 자주 마련되면 좋겠습니다.", group_type: "draw" },
  { department: "대구권지원P", name: "엄태홍", content: "지역별 특성을 반영한 맞춤 지원 정책이 더 늘어나면 좋겠습니다.", group_type: "no_draw" },
  { department: "미등록지역단", name: "임가상", content: "세 번째 테스트 배치의 가짜 이름 접수 데이터입니다.", group_type: "draw" },
  { department: "부천지역단", name: "양진석", content: "실패 사례를 감추기보다 공유하고 배우는 문화로 바뀌면 좋겠습니다.", group_type: "draw" },
  { department: "전주연수소지원P", name: "김태엽", content: "연수 프로그램이 이론 중심에서 실전 시뮬레이션 중심으로 바뀌면 좋겠습니다.", group_type: "no_draw" },
  { department: "동대문지역단", name: "김철홍", content: "신규 고객 유치보다 기존 고객 관리에 더 무게를 두는 방향으로 전환되면 좋겠습니다.", group_type: "draw" },
  { department: "강북지역단", name: "김신혁", content: "조직개편이 잦아 혼란스러운데, 방향성이 안정적으로 유지되는 구조를 바랍니다.", group_type: "draw" },
  { department: "창원지역단", name: "장민제", content: "심심해요", group_type: "draw" },
  { department: "김해지역단", name: "노영록", content: "ㅋㅎㅋㅎㅋㅎㅋㅎㅋㅎㅋㅎㅋㅎㅋㅎ", group_type: "draw" },
  { department: "구포양산지역단", name: "강기원", content: "가나다라", group_type: "draw" },
  { department: "의정부지역단", name: "김진우", content: "설계사 개인기에 의존하기보다 팀 단위 지원 체계로 전환되었으면 합니다.", group_type: "draw" },
  { department: "관동지역단", name: "김양진", content: "숫자로만 평가받는 문화에서 과정의 노력도 함께 인정받는 문화로 전환되면 좋겠습니다.", group_type: "draw" },
  { department: "중동지역단", name: "강세훈", content: "본사 지침이 현장 상황을 좀 더 반영해서 내려오면 좋겠습니다.", group_type: "draw" },
  { department: "계양지역단", name: "권영범", content: "단기 이벤트성 캠페인보다 꾸준함을 인정하는 평가 방식으로 전환되길 바랍니다.", group_type: "draw" },
  { department: "광진지역단", name: "조이화", content: "고객 불만 처리가 매뉴얼 대응 중심에서 진심 어린 공감 중심으로 바뀌었으면 합니다.", group_type: "draw" },
  { department: "수도권2영업추진P", name: "박강노", content: "영업 추진 방식이 단기 실적보다 장기 정착률 중심으로 바뀌었으면 합니다.", group_type: "no_draw" },
  { department: "수도권2CSM지원P", name: "김영택", content: "고객 응대 시스템이 더 직관적으로 개선되면 현장 업무가 훨씬 수월해질 것 같습니다.", group_type: "no_draw" },
  { department: "동부영업추진P", name: "이승후", content: "신입 정착 지원이 초반 몇 달에만 집중되지 않고 꾸준히 이어졌으면 합니다.", group_type: "no_draw" },
  { department: "진주지역단", name: "성태갑", content: "작성테스트 완료", group_type: "draw" },
  { department: "거제통영지역단", name: "김홍배", content: "테스트테스트", group_type: "draw" },
];
